# Generated by Django 5.1.7 on 2025-12-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
    ]
