# Generated by Django 5.1.7 on 2025-12-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_evento_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificado",
            name="arquivo",
            field=models.FileField(blank=True, null=True, upload_to="certificados/"),
        ),
    ]
