# Generated by Django 4.2.7 on 2025-12-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_confirmacao',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
