# Generated by Django 4.2.7 on 2025-12-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_usuario_codigo_confirmacao_usuario_email_confirmado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('usuario_criado', 'Usuário Criado'), ('usuario_login', 'Login de Usuário'), ('evento_criado', 'Evento Criado'), ('evento_alterado', 'Evento Alterado'), ('evento_excluido', 'Evento Excluído'), ('evento_consultado', 'Evento Consultado'), ('inscricao_criada', 'Inscrição Criada'), ('inscricao_cancelada', 'Inscrição Cancelada'), ('presenca_marcada', 'Presença Marcada'), ('certificado_gerado', 'Certificado Gerado'), ('certificado_consultado', 'Certificado Consultado')], max_length=50)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('evento_id', models.IntegerField(blank=True, null=True)),
                ('inscricao_id', models.IntegerField(blank=True, null=True)),
                ('certificado_id', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to='eventos.usuario')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-data_hora'],
            },
        ),
    ]
